// Generated by CIRCT firtool-1.40.0
module MUL_dec(	// <stdin>:3:10
  input  [31:0]  io_a,	// src/main/scala/core/lite/Execute/MUL.scala:8:14
                 io_b,	// src/main/scala/core/lite/Execute/MUL.scala:8:14
  output [255:0] io_y	// src/main/scala/core/lite/Execute/MUL.scala:8:14
);

  wire [15:0] _GEN = {8'h0, io_a[7:0]};	// src/main/scala/core/lite/Execute/MUL.scala:19:{34,63}
  wire [15:0] _GEN_0 = {8'h0, io_b[7:0]};	// src/main/scala/core/lite/Execute/MUL.scala:19:{63,69}
  wire [15:0] _GEN_1 = {8'h0, io_a[15:8]};	// src/main/scala/core/lite/Execute/MUL.scala:19:{34,63}
  wire [15:0] _GEN_2 = {8'h0, io_a[23:16]};	// src/main/scala/core/lite/Execute/MUL.scala:19:{34,63}
  wire [15:0] _GEN_3 = {8'h0, io_a[31:24]};	// src/main/scala/core/lite/Execute/MUL.scala:19:{34,63}
  wire [15:0] _GEN_4 = {8'h0, io_b[15:8]};	// src/main/scala/core/lite/Execute/MUL.scala:19:{63,69}
  wire [15:0] _GEN_5 = {8'h0, io_b[23:16]};	// src/main/scala/core/lite/Execute/MUL.scala:19:{63,69}
  wire [15:0] _GEN_6 = {8'h0, io_b[31:24]};	// src/main/scala/core/lite/Execute/MUL.scala:19:{63,69}
  assign io_y =
    {_GEN_3 * _GEN_6,
     _GEN_2 * _GEN_6,
     _GEN_1 * _GEN_6,
     _GEN * _GEN_6,
     _GEN_3 * _GEN_5,
     _GEN_2 * _GEN_5,
     _GEN_1 * _GEN_5,
     _GEN * _GEN_5,
     _GEN_3 * _GEN_4,
     _GEN_2 * _GEN_4,
     _GEN_1 * _GEN_4,
     _GEN * _GEN_4,
     _GEN_3 * _GEN_0,
     _GEN_2 * _GEN_0,
     _GEN_1 * _GEN_0,
     _GEN * _GEN_0};	// <stdin>:3:10, src/main/scala/core/lite/Execute/MUL.scala:19:63, :22:20
endmodule

module MUL_scala(	// <stdin>:90:10
  input         clock,	// <stdin>:91:11
                reset,	// <stdin>:92:11
  input  [31:0] io_a,	// src/main/scala/core/lite/Execute/MUL.scala:26:14
                io_b,	// src/main/scala/core/lite/Execute/MUL.scala:26:14
  output [63:0] io_y	// src/main/scala/core/lite/Execute/MUL.scala:26:14
);

  wire         co3;	// src/main/scala/core/lite/Execute/MUL.scala:73:14
  wire         co2;	// src/main/scala/core/lite/Execute/MUL.scala:72:14
  wire         co1;	// src/main/scala/core/lite/Execute/MUL.scala:71:14
  wire [255:0] _decoder_io_y;	// src/main/scala/core/lite/Execute/MUL.scala:41:23
  wire [32:0]  sum1 =
    {1'h0,
     _decoder_io_y[223:216],
     _decoder_io_y[159:152],
     _decoder_io_y[103:96],
     _decoder_io_y[87:80]}
    + {1'h0, _decoder_io_y[231:224], _decoder_io_y[167:160], _decoder_io_y[143:128]};	// src/main/scala/core/lite/Execute/MUL.scala:41:23, :49:38, :56:80, :66:19
  wire [16:0]  sum2 =
    {1'h0, _decoder_io_y[207:200], _decoder_io_y[151:144]}
    + {1'h0, _decoder_io_y[215:208], _decoder_io_y[199:192]};	// src/main/scala/core/lite/Execute/MUL.scala:41:23, :49:38, :66:19, :67:19
  wire [32:0]  sum3 = sum1 + {7'h0, co2, sum2, 8'h0};	// src/main/scala/core/lite/Execute/MUL.scala:52:168, :66:19, :67:19, :68:{16,30}, :72:14
  assign co1 = sum1[32];	// src/main/scala/core/lite/Execute/MUL.scala:66:19, :71:14
  assign co2 = sum2[16];	// src/main/scala/core/lite/Execute/MUL.scala:67:19, :72:14
  assign co3 = sum3[32];	// src/main/scala/core/lite/Execute/MUL.scala:68:16, :73:14
  wire [63:0]  subsum4 =
    {14'h0, co3 + co1, sum3, 16'h0}
    + {_decoder_io_y[255:248],
       _decoder_io_y[191:184],
       _decoder_io_y[127:120],
       _decoder_io_y[63:56],
       _decoder_io_y[47:40],
       _decoder_io_y[31:24],
       _decoder_io_y[15:8],
       8'h0}
    + {8'h0,
       _decoder_io_y[239:232],
       _decoder_io_y[175:168],
       _decoder_io_y[111:104],
       _decoder_io_y[55:48],
       _decoder_io_y[39:32],
       _decoder_io_y[23:16],
       8'h0}
    + {8'h0,
       _decoder_io_y[247:240],
       _decoder_io_y[183:176],
       _decoder_io_y[119:112],
       _decoder_io_y[95:88],
       _decoder_io_y[79:64],
       8'h0};	// src/main/scala/core/lite/Execute/MUL.scala:41:23, :49:38, :52:168, :54:125, :68:16, :69:14, :71:14, :73:14, :75:38, :76:22, :77:22, :78:22
  MUL_dec decoder (	// src/main/scala/core/lite/Execute/MUL.scala:41:23
    .io_a (io_a),
    .io_b (io_b),
    .io_y (_decoder_io_y)
  );
  assign io_y = {subsum4[63:8], _decoder_io_y[7:0]};	// <stdin>:90:10, src/main/scala/core/lite/Execute/MUL.scala:41:23, :49:38, :78:22, :79:{18,25}
endmodule

